version: "3.9"
services:
  db:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 7s
      retries: 4
    container_name: "database"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3333:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - my-network
  rabbitmq:
    image: rabbitmq:3.10.1-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network
  web:
    build: ./Application
    container_name: "webApp"
    ports:
      - 8080:80
      - 8081:443
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network
  consumer:
    build: ./Consumer
    container_name: "consumer"
    ports:
      - 3000:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
